// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	common "personalNotificationService/common"

	mock "github.com/stretchr/testify/mock"

	repositories "personalNotificationService/repositories"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSender) Send(_a0 repositories.NotificationChannel, _a1 interface{}, _a2 common.Content) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(repositories.NotificationChannel, interface{}, common.Content) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 repositories.NotificationChannel
//   - _a1 interface{}
//   - _a2 common.Content
func (_e *MockSender_Expecter) Send(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", _a0, _a1, _a2)}
}

func (_c *MockSender_Send_Call) Run(run func(_a0 repositories.NotificationChannel, _a1 interface{}, _a2 common.Content)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(repositories.NotificationChannel), args[1].(interface{}), args[2].(common.Content))
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(_a0 error) *MockSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(repositories.NotificationChannel, interface{}, common.Content) error) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
