// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageProcessor is an autogenerated mock type for the MessageProcessor type
type MockMessageProcessor struct {
	mock.Mock
}

type MockMessageProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageProcessor) EXPECT() *MockMessageProcessor_Expecter {
	return &MockMessageProcessor_Expecter{mock: &_m.Mock}
}

// ProcessMessage provides a mock function with given fields: message
func (_m *MockMessageProcessor) ProcessMessage(message *sarama.ConsumerMessage) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sarama.ConsumerMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageProcessor_ProcessMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMessage'
type MockMessageProcessor_ProcessMessage_Call struct {
	*mock.Call
}

// ProcessMessage is a helper method to define mock.On call
//   - message *sarama.ConsumerMessage
func (_e *MockMessageProcessor_Expecter) ProcessMessage(message interface{}) *MockMessageProcessor_ProcessMessage_Call {
	return &MockMessageProcessor_ProcessMessage_Call{Call: _e.mock.On("ProcessMessage", message)}
}

func (_c *MockMessageProcessor_ProcessMessage_Call) Run(run func(message *sarama.ConsumerMessage)) *MockMessageProcessor_ProcessMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sarama.ConsumerMessage))
	})
	return _c
}

func (_c *MockMessageProcessor_ProcessMessage_Call) Return(_a0 error) *MockMessageProcessor_ProcessMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageProcessor_ProcessMessage_Call) RunAndReturn(run func(*sarama.ConsumerMessage) error) *MockMessageProcessor_ProcessMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageProcessor creates a new instance of MockMessageProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageProcessor {
	mock := &MockMessageProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
